/**
 * بناء فهرس الأبواب (أبواب كتب الحديث التقليدية):
 *  - الأسماء: قاموس عربي ثابت لأسماء الأبواب المعروفة (ليست ترجمة آلية)
 *  - الأحاديث: تُستخرج فعليًا من hadiths[] في ملف كل قسم (المدى في metadata
 *    متداخل في بعض الكتب — الترمذي 38/39 — فلا يُعتمد عليه أبدًا)
 * المخرج: src/index.json الذي يستهلكه التطبيق.
 */
const CDN = "https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1/editions";
const fs = require("fs");
const path = require("path");

const BOOKS: Record<string, string> = {
  "abu-dawud": "ara-abudawud",
  bukhari: "ara-bukhari",
  "ibnu-majah": "ara-ibnmajah",
  malik: "ara-malik",
  muslim: "ara-muslim",
  nasai: "ara-nasai",
  tirmidzi: "ara-tirmidhi",
};

/** أسماء الأبواب التقليدية (مراجعة يدوية ضد القائمة الكاملة 239 عنوانًا) */
const AR: Record<string, string> = {
  "The Book on Purification": "كتاب الطهارة",
  "Purification (Kitab Al-Taharah)": "كتاب الطهارة",
  "The Book of Purification": "كتاب الطهارة",
  "The Book of Purification and its Sunnah": "كتاب الطهارة وسنتها",
  "Purity": "كتاب الطهارة",
  "The Book of Ghusl and Tayammum": "كتاب الغسل والتيمم",
  "The Book of Water": "كتاب المياه",
  "The Book of Menstruation and Istihadah": "كتاب الحيض والاستحاضة",
  "The Times of Prayer": "كتاب أوقات الصلاة",
  "The Book of Salah": "كتاب الصلاة",
  "The Book of the Prayer": "كتاب الصلاة",
  "Prayer": "كتاب الصلاة",
  "Prayer (Kitab Al-Salat)": "كتاب الصلاة",
  "The Book on Salat (Prayer)": "كتاب الصلاة",
  "Establishing the Prayer and the Sunnah Regarding Them": "كتاب إقامة الصلاة والسنة فيها",
  "The Book of the Times (of Prayer)": "كتاب المواقيت",
  "The Book of the Adhan (The Call to Prayer)": "كتاب الأذان",
  "The Book of the Adhan and the Sunnah Regarding It": "كتاب الأذان والسنة فيه",
  "The Book of the Masjids": "كتاب المساجد",
  "The Book On The Mosques And The Congregations": "كتاب المساجد وجماعاتها",
  "The Book of the Qiblah": "كتاب القبلة",
  "The Book of Jumu'ah (Friday Prayer)": "كتاب صلاة الجمعة",
  "The Book on the Day of Friday": "كتاب يوم الجمعة",
  "The Book of the Commencement of the Prayer": "كتاب افتتاح الصلاة",
  "The Book of the Fear Prayer": "كتاب صلاة الخوف",
  "The Book of Shortening the Prayer When Traveling": "كتاب قصر الصلاة في السفر",
  "The Book of Praying for Rain (Al-Istisqa')": "كتاب الاستسقاء",
  "The Book Of The Prayer For Rain (Kitab al-Istisqa')": "كتاب الاستسقاء",
  "The Book of the Prayer for the Two 'Eids": "كتاب صلاة العيدين",
  "The Book on the Two Eids": "كتاب العيدين",
  "The Two 'Ids": "كتاب العيدين",
  "The Book of Eclipses": "كتاب كسوف الشمس",
  "The Eclipse Prayer": "كتاب كسوف الشمس",
  "The Book of Forgetfulness (In Prayer)": "كتاب السهو",
  "Forgetfulness in Prayer": "كتاب السهو",
  "The Book of Leading the Prayer (Al-Imamah)": "كتاب الإمامة والفصل بين المصلين",
  "The Book on Al-Witr": "كتاب الوتر",
  "Prayer (Kitab Al-Salat): Detailed Injunctions about Witr": "كتاب الوتر",
  "Prayer (Kitab Al-Salat): Voluntary Prayers": "كتاب التطوع",
  "The Book of Qiyam Al-Lail (The Night Prayer) and Voluntary Prayers During the Day": "كتاب قيام الليل وتطوع النهار",
  "Prayer in Ramadan": "كتاب قيام رمضان",
  "I'tikaf in Ramadan": "كتاب الاعتكاف",
  "The Book on Traveling": "كتاب السفر",
  "Prayer (Kitab Al-Salat): Detailed Rules of Law about the Prayer during Journey": "كتاب صلاة السفر",
  "The Book of Zakah": "كتاب الزكاة",
  "The Book on Zakat": "كتاب الزكاة",
  "Zakat": "كتاب الزكاة",
  "Zakat (Kitab Al-Zakat)": "كتاب الزكاة",
  "The Chapters Regarding Zakat": "كتاب الزكاة",
  "The Book on Fasting": "كتاب الصيام",
  "Fasting": "كتاب الصيام",
  "Fasting (Kitab Al-Siyam)": "كتاب الصيام",
  "The Book of Hajj": "كتاب الحج",
  "The Book on Hajj": "كتاب الحج",
  "Hajj": "كتاب الحج",
  "Chapters on Hajj Rituals": "كتاب مناسك الحج",
  "The Rites of Hajj (Kitab Al-Manasik Wa'l-Hajj)": "كتاب المناسك والحج",
  "The Book on Marriage": "كتاب النكاح",
  "The Book of Marriage": "كتاب النكاح",
  "The Chapters on Marriage": "كتاب النكاح",
  "Marriage": "كتاب النكاح",
  "Marriage (Kitab Al-Nikah)": "كتاب النكاح",
  "The Book on Suckling": "كتاب الرضاع",
  "Suckling": "كتاب الرضاع",
  "The Book on Divorce and Li'an": "كتاب الطلاق واللعان",
  "The Book of Divorce": "كتاب الطلاق",
  "The Chapters on Divorce": "كتاب الطلاق",
  "Divorce": "كتاب الطلاق",
  "Divorce (Kitab Al-Talaq)": "كتاب الطلاق",
  "The Book on Business": "كتاب البيوع",
  "The Chapters on Business Transactions": "كتاب البيوع",
  "Business Transactions": "كتاب البيوع",
  "Commercial Transactions (Kitab Al-Buyu)": "كتاب البيوع",
  "The Book of Financial Transactions": "كتاب البيوع",
  "Wages (Kitab Al-Ijarah)": "كتاب الإجارة",
  "The Chapters on Pawning": "كتاب الرهن",
  "The Chapters on Pre-emption": "كتاب الشفعة",
  "Pre-emption in Property": "كتاب الشفعة",
  "The Chapters on Lost Property": "كتاب لقطة",
  "The Book of Lost and Found Items": "كتاب لقطة",
  "The Chapters on Charity": "كتاب الصدقات",
  "Sadaqa": "كتاب الصدقات",
  "The Book of Gifts": "كتاب الهبات",
  "The Chapters on Gifts": "كتاب الهبات",
  "The Book of Presents": "كتاب الهدايا",
  "The Book of Endowments": "كتاب الأحباس",
  "The Book of Wills": "كتاب الوصايا",
  "The Chapters on Wills": "كتاب الوصايا",
  "Wills (Kitab Al-Wasaya)": "كتاب الوصايا",
  "Wills and Testaments": "كتاب الوصايا",
  "Chapters On Wasaya (Wills and Testament)": "كتاب الوصايا",
  "The Book of al-Fara' and al-'Atirah": "كتاب الفَرَع والعَتيرة",
  "The Book of ar-Ruqba": "كتاب الرقبة",
  "The Book of 'Umra": "كتاب العمرى",
  "The Book of Agriculture": "كتاب المزارعة",
  "Sharecropping": "كتاب المزارعة",
  "Renting Land": "كتاب أجرة الأرض",
  "Qirad": "كتاب القِراض",
  "The Qibla": "كتاب القبلة",
  "The Qur'an": "كتاب القرآن",
  "The Book on the Description of Hellfire": "كتاب صفة جهنم",
  "Burials": "كتاب الجنائز",
  "The Book of Fasting": "كتاب الصيام",
  "Jahannam": "كتاب جهنم",
  "The Book on Blood Money": "كتاب الدیات",
  "The Chapters on Blood Money": "كتاب الدیات",
  "Blood-Money": "كتاب الدیات",
  "The Book of Oaths (qasamah), Retaliation and Blood Money": "كتاب القسامة والقصاص والدیات",
  "Types of Blood-Wit (Kitab Al-Diyat)": "كتاب الدیات",
  "The Book on Legal Punishments (Al-Hudud)": "كتاب الحدود",
  "The Chapters on Legal Punishments": "كتاب الحدود",
  "Prescribed Punishments (Kitab Al-Hudud)": "كتاب الحدود",
  "Hudud": "كتاب الحدود",
  "The Book of Cutting off the Hand of the Thief": "كتاب قطع السارق",
  "The Book on Hunting": "كتاب الصيد",
  "The Book of Hunting and Slaughtering": "كتاب الصيد والذبح",
  "Chapters on Hunting": "كتاب الصيد",
  "Game": "كتاب الصيد",
  "Game (Kitab Al-Said)": "كتاب الصيد",
  "The Book on Sacrifices": "كتاب الأضاحي",
  "Chapters on Sacrifices": "كتاب الأضاحي",
  "Sacrifice (Kitab Al-Dahaya)": "كتاب الذباح",
  "The Book of ad-Dahaya (Sacrifices)": "كتاب الأضاحي",
  "Sacrificial Animals": "كتاب الأضاحي",
  "Slaughtering Animals": "كتاب الذبح",
  "Chapters on Slaughtering": "كتاب الذبح",
  "The 'Aqiqa": "كتاب العقيقة",
  "The Book of al-'Aqiqah": "كتاب العقيقة",
  "The Book of al-Bay'ah": "كتاب البيعة",
  "The Oath of Allegiance": "كتاب البيعة",
  "The Book of Jihad": "كتاب الجهاد",
  "The Book on Jihad": "كتاب الجهاد",
  "The Chapters on Jihad": "كتاب الجهاد",
  "Jihad": "كتاب الجهاد",
  "Jihad (Kitab Al-Jihad)": "كتاب الجهاد",
  "The Book on Military Expeditions": "كتاب المغازي",
  "The Book on Virtues of Jihad": "كتاب فضل الجهاد",
  "The Book of Fighting [The Prohibition of Bloodshed]": "كتاب حرس الدماء",
  "Tribute, Spoils, and Rulership (Kitab Al-Kharaj, Wal-Fai' Wal-Imarah)": "كتاب الخراج والإمرة",
  "The Book of Distribution of Al-Fay'": "كتاب الفيء",
  "The Book of Funerals": "كتاب الجنائز",
  "The Book on Jana''iz (Funerals)": "كتاب الجنائز",
  "Chapters Regarding Funerals": "كتاب الجنائز",
  "Funerals (Kitab Al-Jana'iz)": "كتاب الجنائز",
  "Chapters on Food": "كتاب الأطعمة",
  "The Book on Food": "كتاب الأطعمة",
  "Foods (Kitab Al-At'imah)": "كتاب الأطعمة",
  "Chapters on Drinks": "كتاب الأشربة",
  "The Book of Drinks": "كتاب الأشربة",
  "The Book on Drinks": "كتاب الأشربة",
  "Drinks": "كتاب الأشربة",
  "Drinks (Kitab Al-Ashribah)": "كتاب الأشربة",
  "Chapters on Medicine": "كتاب الطب",
  "Medicine (Kitab Al-Tibb)": "كتاب الطب",
  "Chapters on Dress": "كتاب اللباس",
  "The Book on Clothing": "كتاب اللباس",
  "Clothing (Kitab Al-Libas)": "كتاب اللباس",
  "Dress": "كتاب اللباس",
  "The Book of Adornment": "كتاب الزينة",
  "Combing the Hair (Kitab Al-Tarajjul)": "كتاب الترجّل",
  "Signet-Rings (Kitab Al-Khatam)": "كتاب الخاتم",
  "Hot Baths (Kitab Al-Hammam)": "كتاب الحمّام",
  "The Book of Horses, Races and Shooting": "كتاب الخيل والسباق والرمي",
  "The Book on Faith": "كتاب الإيمان",
  "The Book Of Faith and its Signs": "كتاب الإيمان وفعاله",
  "The Book on Vows and Oaths": "كتاب النذور والأيمان",
  "Vows and Oaths": "كتاب النذور والأيمان",
  "Oaths and Vows (Kitab Al-Aiman Wa Al-Nudhur)": "كتاب الأيمان والنذور",
  "The Book of the Kind Treatment of Women": "كتاب رفق النساء",
  "The Book of the Etiquette of Judges": "كتاب آداب القضاة",
  "The Book of The At-Tatbiq (Clasping One's Hands Together)": "كتاب التطبيق في الصلاة",
  "The Chapters On Judgements From The Messenger of Allah": "كتاب الأحكام",
  "Judgements": "كتاب الأحكام",
  "The Chapters on Rulings": "كتاب الأحكام",
  "The Office of the Judge (Kitab Al-Aqdiyah)": "كتاب الأقضية",
  "The Book of Manumission of Slaves": "كتاب العتق",
  "The Chapters on Manumission (of Slaves)": "كتاب العتق",
  "The Mukatab": "كتاب المكاتب",
  "The Mudabbar": "كتاب المُدبَّر",
  "Setting Free and Wala'": "كتاب العتق والولاء",
  "Chapters On Inheritance": "كتاب الفرائض",
  "Fara'id": "كتاب الفرائض",
  "Shares of Inheritance (Kitab Al-Fara'id)": "كتاب الفرائض",
  "Chapters on Shares of Inheritance": "كتاب الفرائض",
  "Chapters On Wala' And Gifts": "كتاب الولاء والهبة",
  "Chapters on Seeking Permission": "كتاب الاستئذان",
  "Chapters on Manners": "كتاب الأداب",
  "Etiquette": "كتاب الأدب",
  "General Behavior (Kitab Al-Adab)": "كتاب الأدب",
  "Good Character": "كتاب حسن الخلق",
  "Chapters on Supplication": "كتاب الدعوات",
  "Supplication": "كتاب الدعاء",
  "The Book of Seeking Refuge with Allah": "كتاب الاستعاذة",
  "Chapters on Recitation": "كتاب قراءة القرآن",
  "Chapters on The Virtues of the Qur'an": "كتاب فضل القرآن",
  "Chapters on Tafsir": "كتاب التفسير",
  "Chapters on Dreams": "كتاب الرؤيا",
  "Interpretation of Dreams": "كتاب تعبير الرؤيا",
  "Visions": "كتاب الرؤيا",
  "Chapters On Al-Qadar": "كتاب القدر",
  "The Chapters on Expiation": "كتاب الكفارات",
  "Chapters On Al-Fitan": "كتاب الفتن",
  "Trials and Fierce Battles (Kitab Al-Fitan Wa Al-Malahim)": "كتاب الفتن والملاحم",
  "Battles (Kitab Al-Malahim)": "كتاب الملاحم",
  "The Promised Deliverer (Kitab Al-Mahdi)": "كتاب المهدي",
  "Chapters On Zuhd": "كتاب الزهد",
  "Zuhd": "كتاب الزهد",
  "Chapters on the description of Paradise": "كتاب صفة الجنة",
  "Chapters on the description of the Day of Judgement, Ar-Riqaq, and Al-Wara'": "كتاب صفة القيامة والرقاق والورع",
  "Chapters on Virtues": "كتاب المناقب",
  "Chapters on Righteousness And Maintaining Good Relations With Relatives": "كتاب البر وصلة الأرحام",
  "Chapters On Dreams": "كتاب الرؤيا",
  "Chapters On Witnesses": "كتاب الشهادات",
  "Chapters on Knowledge": "كتاب العلم",
  "Knowledge (Kitab Al-Ilm)": "كتاب العلم",
  "Knowledge": "كتاب العلم",
  "Chapters on Parables": "كتاب الأمثال",
  "Asking for Rain": "كتاب الاستسقاء",
  "Tribulations": "كتاب الفتن",
  "Model Behavior of the Prophet (Kitab Al-Sunnah)": "كتاب السنة",
  "Dialects and Readings of the Qur'an (Kitab Al-Huruf Wa Al-Qira'at)": "كتاب الحروف والقراءات",
  "Divination and Omens (Kitab Al-Kahanah Wa Al-Tatayyur)": "كتاب الكهانة والتطير",
  "The Oath of Qasama": "كتاب قسامة",
  "The Description of the Prophet, may Allah Bless Him and Grant Him Peace": "كتاب صفة النبي ﷺ",
  "The Names of the Prophet, may Allah Bless Him and Grant Him Peace": "كتاب أسماء النبي ﷺ",
  "The Evil Eye": "كتاب العين",
  "Hair": "كتاب الشعر",
  "Greetings": "كتاب السلام",
  "Speech": "كتاب الكلام",
  "General Subjects": "كتاب مسائل عامة",
  "Madina": "كتاب المدينة",
  "The Decree": "كتاب القدر",
  "Prayer in Congregation": "كتاب الجماعة والامتلاء",
  "Shortening the Prayer": "كتاب قصر الصلاة",
  "Tahajjud": "كتاب تهجد",
  "The Fear Prayer": "كتاب خوف",
  "Fear Prayer": "كتاب صلاة الخوف",
  "Jumu'a": "كتاب الجمعة",
  "Prayer (Kitab Al-Salat): Prostration while reciting the Qur'an": "كتاب سجود التلاوة",
  "Prayer (Kitab Al-Salat): Detailed Injunctions about Ramadan": "كتاب تفاصيل رمضان",
  "The Supplication of the Unjustly Wronged": "دعوة المظلوم",
  // أسماء البخاري ومسلم القصيرة (صيغة المصدر لهذين الكتابين)
  Revelation: "كتاب بدء الوحي",
  Belief: "كتاب الإيمان",
  Faith: "كتاب الإيمان",
  "The Book of Belief": "كتاب الإيمان",
  "The Book of Faith": "كتاب الإيمان",
  "Obligatory Alms": "كتاب الزكاة",
  Pilgrimage: "كتاب الحج",
  "The Two Festivals": "كتاب العيدين",
  "Divine Will (Al-Qadar)": "كتاب القدر",
  "Virtues and Merits of the Prophet (pbuh) and his Companions": "كتاب المناقب",
  "The Book of Mushaf (The Book of Tafsir)": "كتاب التفسير",
  Afflictions: "كتاب الفتن",
  "Holding Fast to the Qur'an and Sunnah": "كتاب الاعتصام بالكتاب والسنة",
  "To make the Heart Tender (Ar-Riqaq)": "كتاب الرقاق",
  "Dress (Libas)": "كتاب اللباس",
  "Good Manners and Form (Al-Adab)": "كتاب الأدب",
  "Asking Permission (Al-Istidhan)": "كتاب الاستئذان",
  Invocations: "كتاب الدعوات",
  "Foods (Meals)": "كتاب الأطعمة",
  "Prophetic Commentary on the Qur'an (Tafseer of the Prophet (pbuh))": "كتاب تفسير النبي ﷺ",
  "Virtues of the Qur'an": "كتاب فضل القرآن",
  Wedlock: "كتاب النكاح",
  "Sales and Trade": "كتاب البيوع",
  "Shares of Inheritance (Al-Faraa'id)": "كتاب الفرائض",
  "Punishment of Disbelievers by Allah": "كتاب أهل الكفر والأحكام",
  "Judgments (Ahkaam)": "كتاب الأحكام",
  "Wishes and Hopes": "كتاب الأماني",
  "Dealing with apostates": "كتاب المرتدين",
  "Pre-emption (Al-Khiyar)": "كتاب الشفعة",
  "Hiring (Ijara)": "كتاب الإجارة",
  "Agriculture (Al-Muzara'ah)": "كتاب المزارعة",
  "Water and Irrigation": "كتاب الماء والسقي",
  Loans: "كتاب القروض",
  "Freeing Slaves": "كتاب العتق",
  "Representation or Authorization (Business Agency)": "كتاب الوكالة",
  "Cultivation of the Land": "كتاب الحرث",
  "Borrowing and Lending": "كتاب الاستقراض",
  "Civil Laws": "كتاب القضاء",
  Fighting: "كتاب الجهاد والسير",
  "Military Expeditions led by the Prophet (pbuh) (Al-Maghaazi)": "كتاب المغازي",
  Commentary: "كتاب التفسير",
  "Stories of the Prophets": "كتاب قصص الأنبياء",
  "Virtues of Madinah": "كتاب فضل المدينة",
  // أسماء البخاري بترجمة USC-MSA (الصيغة المعتمدة في المصدر) — مقابلاتها التقليدية
  "Ablutions (Wudu')": "كتاب الوضوء",
  "Bathing (Ghusl)": "كتاب الغسل",
  "Menstrual Periods": "كتاب الحيض",
  "Rubbing hands and feet with dust (Tayammum)": "كتاب التيمم",
  "Prayers (Salat)": "كتاب الصلاة",
  "Times of the Prayers": "كتاب مواقيت الصلاة",
  "Call to Prayers (Adhaan)": "كتاب الأذان",
  "Friday Prayer": "كتاب الجمعة",
  "The Two Festivals (Eids)": "كتاب العيدين",
  "Witr Prayer": "كتاب الوتر",
  "Invoking Allah for Rain (Istisqaa)": "كتاب الاستسقاء",
  Eclipses: "كتاب الكسوف",
  "Prostration During Recital of Qur'an": "كتاب سجود التلاوة",
  "Shortening the Prayers (At-Taqseer)": "كتاب التقصير",
  "Prayer at Night (Tahajjud)": "كتاب التهجد",
  "Virtues of Prayer at Masjid Makkah and Madinah": "كتاب فضل الصلاة في مسجد مكة والمدينة",
  "Actions while Praying": "كتاب الأفعال في الصلاة",
  "Funerals (Al-Janaa'iz)": "كتاب الجنائز",
  "Obligatory Charity Tax (Zakat)": "كتاب الزكاة",
  "Hajj (Pilgrimage)": "كتاب الحج",
  "`Umrah (Minor pilgrimage)": "كتاب العمر",
  "Pilgrims Prevented from Completing the Pilgrimage": "كتاب المحرم الذي يعوقه عدو",
  "Penalty of Hunting while on Pilgrimage": "كتاب جزاء الصيد للمحرم",
  "Praying at Night in Ramadaan (Taraweeh)": "كتاب قيام رمضان",
  "Virtues of the Night of Qadr": "كتاب فضل ليلة القدر",
  "Retiring to a Mosque for Remembrance of Allah (I'tikaf)": "كتاب الاعتكاف",
  "Sales in which a Price is paid for Goods to be Delivered Later (As-Salam)": "كتاب السلم",
  "Shuf'a": "كتاب الشفعة",
  Hiring: "كتاب الإجارة",
  "Transferance of a Debt from One Person to Another (Al-Hawaala)": "كتاب الحوالة",
  Kafalah: "كتاب الكفالة",
  "Representation, Authorization, Business by Proxy": "كتاب الوكالة",
  Agriculture: "كتاب المزارعة",
  "Distribution of Water": "كتاب المساقاة",
  "Loans, Payment of Loans, Freezing of Property, Bankruptcy": "كتاب القروض",
  Khusoomaat: "كتاب الخصومات",
  "Lost Things Picked up by Someone (Luqatah)": "كتاب لقطة",
  Oppressions: "كتاب المظالم",
  Partnership: "كتاب الشركة",
  Mortgaging: "كتاب الرهن",
  "Manumission of Slaves": "كتاب العتق",
  Makaatib: "كتاب المكاتب",
  Gifts: "كتاب الهبات",
  Witnesses: "كتاب الشهادات",
  Peacemaking: "كتاب الصلح",
  Conditions: "كتاب الشروط",
  "Wills and Testaments (Wasaayaa)": "كتاب الوصايا",
  "Fighting for the Cause of Allah (Jihaad)": "كتاب الجهاد والسير",
  "One-fifth of Booty to the Cause of Allah (Khumus)": "كتاب خمس الغنيمة",
  "Jizyah and Mawaada'ah": "كتاب الجزية والموادعة",
  "Beginning of Creation": "كتاب بدء الخلق",
  Prophets: "كتاب أحاديث الأنبياء",
  "Companions of the Prophet": "كتاب فضل الصحابة",
  "Merits of the Helpers in Madinah (Ansaar)": "كتاب فضل الأنصار",
  "Wedlock, Marriage (Nikaah)": "كتاب النكاح",
  "Supporting the Family": "كتاب النفقات",
  "Food, Meals": "كتاب الأطعمة",
  "Sacrifice on Occasion of Birth (`Aqiqa)": "كتاب العقيقة",
  "Hunting, Slaughtering": "كتاب الذبائح والصيد",
  "Al-Adha Festival Sacrifice (Adaahi)": "كتاب الأضاحي",
  Patients: "كتاب المرضى",
  Medicine: "كتاب الطب",
  "Asking Permission": "كتاب الاستئذان",
  "Oaths and Vows": "كتاب الأيمان والنذور",
  "Expiation for Unfulfilled Oaths": "كتاب كفارات الأيمان",
  "Laws of Inheritance (Al-Faraa'id)": "كتاب الفرائض",
  "Limits and Punishments set by Allah (Hudood)": "كتاب الحدود",
  "Blood Money (Ad-Diyat)": "كتاب الدیات",
  Apostates: "كتاب الردة",
  "(Statements made under) Coercion": "كتاب الإكراه",
  Tricks: "كتاب الحيل",
  "Afflictions and the End of the World": "كتاب الفتن",
  Wishes: "كتاب الأماني",
  "Accepting Information Given by a Truthful Person": "كتاب الأخبار الفرد",
  "Oneness, Uniqueness of Allah (Tawheed)": "كتاب التوحيد",
  // أسماء مسلم بصيغة المصدر "The Book of X" — مقابلاتها التقليدية
  "The Book of Menstruation": "كتاب الحيض",
  "The Book of Prayers": "كتاب الصلاة",
  "The Book of Mosques and Places of Prayer": "كتاب المساجد ومواضع الصلاة",
  "The Book of Prayer - Travellers": "كتاب صلاة المسافرين وقصرها",
  "The Book of Prayer - Friday": "كتاب صلاة الجمعة",
  "The Book of Prayer - Two Eids": "كتاب صلاة العيدين",
  "The Book of Prayer - Rain": "كتاب صلاة الاستسقاء",
  "The Book of Prayer - Eclipses": "كتاب صلاة الكسوف",
  "The Book of Prayer - Funerals": "كتاب الجنائز",
  "The Book of Zakat": "كتاب الزكاة",
  "The Book of I'tikaf": "كتاب الاعتكاف",
  "The Book of Pilgrimage": "كتاب الحج",
  "The Book of Suckling": "كتاب الرضاع",
  "The Book of Invoking Curses": "كتاب اللعان",
  "The Book of Emancipating Slaves": "كتاب العتق",
  "The Book of Transactions": "كتاب البيوع",
  "The Book of Musaqah": "كتاب المساقاة",
  "The Book of the Rules of Inheritance": "كتاب الفرائض",
  "The Book of Vows": "كتاب النذور",
  "The Book of Oaths": "كتاب الأيمان",
  "The Book of Oaths, Muharibin, Qasas (Retaliation), and Diyat (Blood Money)": "كتاب الأيمان والمحاربين والقصاص والدیات",
  "The Book of Legal Punishments": "كتاب الحدود",
  "The Book of Judicial Decisions": "كتاب الأقضية",
  "The Book of Lost Property": "كتاب اللقطات",
  "The Book of Jihad and Expeditions": "كتاب الجهاد والسير",
  "The Book on Government": "كتاب الإمارة",
  "The Book of Hunting, Slaughter, and what may be Eaten": "كتاب الصيد والذبائح",
  "The Book of Sacrifices": "كتاب الأضاحي",
  "The Book of Clothes and Adornment": "كتاب اللباس والزينة",
  "The Book of Manners and Etiquette": "كتاب الآداب",
  "The Book of Greetings": "كتاب السلام",
  "The Book Concerning the Use of Correct Words": "كتاب الألفاظ من السنة",
  "The Book of Poetry": "كتاب الشعر",
  "The Book of Dreams": "كتاب الرؤيا",
  "The Book of Virtues": "كتاب الفضائل",
  "The Book of the Merits of the Companions": "كتاب فضائل الصحابة",
  "The Book of Virtue, Enjoining Good Manners, and Joining of the Ties of Kinship": "كتاب البر وصلة الأرحام",
  "The Book of Destiny": "كتاب القدر",
  "The Book of Knowledge": "كتاب العلم",
  "The Book Pertaining to the Remembrance of Allah, Supplication, Repentance and Seeking Forgiveness": "كتاب الذكر والدعاء والتوبة والاستغفار",
  "The Book of Heart-Melting Traditions": "كتاب الرقاق",
  "The Book of Repentance": "كتاب التوبة",
  "Characteristics of The Hypocrites And Rulings Concerning Them": "كتاب صفة المنافقين وأحكامهم",
  "Characteristics of the Day of Judgment, Paradise, and Hell": "كتاب صفة القيامة والجنة والنار",
  "The Book of Paradise, its Description, its Bounties and its Inhabitants": "كتاب الجنة وصفة نعيمها وأهلها",
  "The Book of Tribulations and Portents of the Last Hour": "كتاب الفتن وأشراط الساعة",
  "The Book of Zuhd and Softening of Hearts": "كتاب الزهد والرقاق",
  "The Book of Commentary on the Qur'an": "كتاب التفسير",
};

async function getJson(url: string): Promise<any> {
  // شبكة البيئة متقطعة أحيانًا — محاولتان قبل الاستسلام (القسم يُتخطى بصمت).
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const r = await fetch(url);
      if (!r.ok) return null;
      return await r.json();
    } catch {
      if (attempt === 1) return null;
      await new Promise((resolve) => setTimeout(resolve, 800));
    }
  }
  return null;
}

(async () => {
  const index: Record<string, Array<{ section: number; titleAr: string; titleEn: string; hadiths: number[] }>> = {};
  const unknown: string[] = [];

  for (const [slug, ed] of Object.entries(BOOKS)) {
    index[slug] = [];
    for (let n = 1; n <= 130; n++) {
      const j = await getJson(`${CDN}/${ed}/sections/${n}.json`);
      if (!j) continue;
      const sec = j.metadata?.section ?? {};
      const keys = Object.keys(sec);
      for (const key of keys) {
        const titleEn = String(sec[key]).trim();
        const titleAr = AR[titleEn];
        if (!titleAr) {
          unknown.push(titleEn);
        }
        // الأحاديث الفعلية من المصفوفة — لا من المدى المتداخل
        const hadiths = (j.hadiths ?? [])
          .map((h: any) => h.hadithnumber)
          .filter((x: any) => Number.isInteger(x));
        index[slug].push({
          section: Number(key),
          titleAr: titleAr ?? titleEn, // fallback: الإنجليزية حتى المراجعة
          titleEn,
          hadiths,
        });
      }
    }
    index[slug].sort((a, b) => a.section - b.section);
  }

  fs.mkdirSync("assets/hadith-index", { recursive: true });
  fs.writeFileSync(
    "assets/hadith-index/index.json",
    JSON.stringify({ generatedAt: new Date().toISOString(), books: index }),
    "utf8",
  );
  console.log("UNKNOWN TITLES (بلا مقابل موثوق — بقيت إنجليزية):");
  console.log([...new Set(unknown)].join("\n") || "(لا شيء)");
  console.log("DONE: assets/hadith-index/index.json");
})();
